# -*- coding: utf-8 -*-
"""text to voice .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FUdK0uROOVfpvUqPb8wkmTJnjllYrW9b
"""

!pip install gTTS

from gtts import gTTS
from IPython.display import Audio, display

# Get text from user
text = input("Enter the text you want to convert to speech: ")

# Convert text to speech
tts = gTTS(text=text, lang='en', slow=False)

# Save the audio
tts.save("output.mp3")

print("Audio saved as output.mp3")

# Play the audio
display(Audio("output.mp3", autoplay=True))