# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FfWMEZtbsIPeYHGDrnZE-tYYHImYhLLp
"""

!pip install -q transforms datasets accelerate

data = [
    {
        "question": "What is the college name?",
        "answer": "The college name is MIT college."
    },
    {
        "question": "Where is the college located?",
        "answer": "The college is located in Mysuru, Karnataka."
    },
    {
        "question": "What courses are offered?",
        "answer": "The college offers B.E, B.Tech and M.Tech courses."
    },
    {
        "question": "Does the college provide hostel facilities?",
        "answer": "Yes, the college provides hostel facilities."
    },
    {
        "question": "Does the college provide transportation?",
        "answer": "Yes, transportation facilities are available."
    }
]

texts = []
for item in data:
    text =(
        "Question: " + item["question"] + "\n" +
        "Answer: " + item["answer"]
    )
    texts.append(text)

for text in texts:
    print(text)
    print()

from transformers import AutoTokenizer
from transformers import AutoModelForCausalLM

model_name = "openai-community/gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token

from datasets import Dataset
dataset = Dataset.from_dict({"text": texts})
print(dataset)

def tokenize(example):
  return tokenizer(
      example["text"],
      truncation=True,
      padding="max_length",
      max_length=64
  )
dataset=dataset.map(tokenize)

from transformers import TrainingArguments
from transformers import Trainer
from transformers import DataCollatorForLanguageModeling

data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args=TrainingArguments(
    output_dir="./my_gpt2",
    num_train_epochs=10,
    per_device_train_batch_size=1,
    logging_steps=1,
    report_to="none"
)

trainer=Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=dataset
)

trainer.train()

trainer.save_model("./my_gpt2")
tokenizer.save_pretrained("./my_gpt2")

from transformers import pipeline

generators = pipeline(
    "text-generation",
    model="./my_gpt2",
    tokenizer="./my_gpt2"
)

question="What courses are offered?"
prompt=(
    "Question:"+question+"\nAnswer:"
)
result=generators(prompt, max_new_tokens=30,do_sample=False)
print(result[0]["generated_text"])

def ask(question):
  prompt = (
      "Question: " + question + "\nAnswer:"
  )
  result = generators(prompt, max_new_tokens=30, do_sample=False)
  answer = result[0]["generated_text"]

print(ask("where the college is"))

# 1. Upload
from google.colab import files #https://tinyurl.com/mittainai
files.upload()

# 2. Read
import pandas as pd
df = pd.read_csv("college_dataset.csv")

# 3. Convert Q&A to text
texts = []

for _, row in df.iterrows():
    texts.append(
        "Question: " + str(row["Question"]) +
        "\nAnswer: " + str(row["Answer"])
    )

# 4. Create dataset
from datasets import Dataset

dataset = Dataset.from_dict({
    "text": texts
})

# 5. Check
print(dataset)