# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ogpgty8R82FRzA6gt6dmjPzeKZyUXhCF
"""

!pip install -q transformers sentence-transformers chromadb pypdf accelerate

from google.colab import files
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]
print("Uploaded:", pdf_path)

from pypdf import PdfReader
reader = PdfReader(pdf_path)
documents = []
for page_number, page in enumerate(reader.pages):
    text = page.extract_text()
    if text:
        documents.append({"text":text,"page":page_number
                          +1})
print("Pages loaded:",len(documents))

print(documents[0]["text"][:2000])

def create_chunks(documents,chunk_size=1000, overlap=200):
  chunks = []
  for doc in documents:
    text = doc["text"]
    page = doc["page"]
    start = 0
    while start < len(text):
      end = start + chunk_size
      chunk = text[start:end]
      chunks.append({"text":chunk,"page":page})
      start = end - overlap
  return chunks
chunks = create_chunks(documents)
print("Total chunks:",len(chunks))

print(chunks[0]["text"])
print("Paage:",chunks[0]["page"])

from sentence_transformers import SentenceTransformer
embedding_model=SentenceTransformer("BAAI/bge-small-en-v1.5")

texts=[chunk["text"] for chunk in chunks]
embeddings=embedding_model.encode(texts,normalize_embeddings=True,show_progress_bar=True)
print("Embedding shape:",embeddings.shape)

import chromadb
client=chromadb.Client()
collection=client.get_or_create_collection(name="college_rag")

collection.add(
    ids=[str(i) for i in range(len(chunks))],
    documents=texts,
    embeddings=embeddings.tolist(),
    metadatas=[
        {"page":chunk["page"]} for chunk in chunks
    ]
)
print("chunks stored:", collection.count())

def retrieve(question,k=3):
  question_embedding=embedding_model.encode([question],normalize_embeddings=True)[0]
  results=collection.query(
      query_embeddings=[
          question_embedding.tolist()
      ],
      n_results=k
  )
  return results

question = "What is the hostel fee?"
results = retrieve(question)
for i, text in enumerate(results["documents"][0]):
    print("\nRESULT", i + 1)
    print(text)
print(
    "Page:",
    results["metadatas"][0][i]["page"],
)

print("-"* 50)

from transformers import AutoTokenizer, AutoModelForCausalLM
model_name = "Qwen/Qwen2.5-1.5B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(
model_name
)

model = AutoModelForCausalLM.from_pretrained(
model_name,
device_map="auto",
torch_dtype="auto",
)

def generate_answer(question,context):
  prompt = f"""
You are a helpful assistant.
Answer the question using ONLY the provided context.
If the answer is not available in the context,
say:
"No information on the provided document."
Context:
{context}
Question:
{question}
Answer:
"""
  messages = [
          {
              "role": "user",
              "content": prompt,
          }
      ]
  text = tokenizer.apply_chat_template(
          messages,
          tokenize=False,
          add_generation_prompt=True

      )
  inputs = tokenizer(
          text,
          return_tensors="pt"
      ).to(model.device)
  outputs = model.generate(
          **inputs,
          max_new_tokens=200,
          do_sample=False
      )
  answer = tokenizer.decode(
          outputs[0][inputs["input_ids"].shape[1]:],
          skip_special_tokens=True
      )
  return answer

def rag(question):
  results = retrieve(question)
  documents = results["documents"][0]
  context="\n\n".join (documents)
  answer = generate_answer(
      question,
      context
  )
  return answer, results

question = "What is supervised learning"
answer, results = rag(question)
print("QUESTION:")
print(question)
print("\nANSWER:")
print(answer)

while True:
  question = input("\nAsk a question: ")
  if question.lower() == "exit":
    print("Goodbye!")
    break
  answer, results = rag(question)

  print("\nANSWER:")
  print(answer)
  print("\nSources:")
  for metadata in results["metadatas"][0]:
    print(f"Page: {metadata['page']}")

